let g:vimfiles = fnamemodify($MYVIMRC, ":p:h")
if empty(glob(g:vimfiles . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.vimfiles.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin(vimfiles.'/plugged')
Plug 'ghifarit53/tokyonight-vim'
Plug 'airblade/vim-gitgutter'
Plug 'DrTom/fsharp-vim'
call plug#end()

" Activate Editorconfig builtin plugin
packadd! editorconfig
" [[ Colorscheme ]]
set termguicolors

let g:tokyonight_style = 'night' " available: night, storm
let g:tokyonight_enable_italic = 1

colorscheme tokyonight

" [[ Options ]]
set number
syntax enable
set nocompatible
filetype plugin on

" [[ Fuzzy finder ]]
set path+=**
set wildmenu

" [[ File Browser ]]
let g:netrw_banner=0
let g:netrw_nrowse_split=4
let g:netrw_altv=1
let g:netrw_liststyle=3
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

" [[ GitGutter ]]
function! GitStatus()
  let [a,m,r] = GitGutterGetHunkSummary()
  return printf('+%d ~%d -%d', a, m, r)
endfunction

" [[ Statusline ]]
set statusline+=%{GitStatus()}

" [[ Templates ]]
function LoadTemplate()
	let l:template = g:vimfiles .'/templates/skeleton.'.expand("<afile>:e")
	silent! execute '0r '. l:template
	" Placeholder {%FILENAME%} with current filename
	silent %s/{%FILENAME%}/\=expand("%:t:r")/g
endfunction

autocmd BufNewFile *.* call LoadTemplate()
nnoremap <Plug>GoToNextPlaceholder :call search('{%[^%]*%}')<CR>va{
imap <silent> <C-q><C-e> <C-v><C-a><C-]><Esc><Plug>GoToNextPlaceholder
nmap <silent> <C-q><C-q> <Plug>GoToNextPlaceholder
imap <silent> <C-q><C-q> <Esc><Plug>GoToNextPlaceholder
vmap <silent> <C-q><C-q> <Esc><Plug>GoToNextPlaceholder
